-- Script for creation of the CUSTOM Schema --

CREATE TABLESPACE "CUSTOMDAT" LOGGING
DATAFILE 'CUSTOMDAT.dbf' SIZE 512M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE "CUSTOMTMP"
TEMPFILE 'CUSTOMTMP.dbf' SIZE 256M
AUTOEXTEND ON;

CREATE USER "CUSTOM" PROFILE "DEFAULT" IDENTIFIED BY "CUSTOM"
DEFAULT TABLESPACE "CUSTOMDAT" TEMPORARY TABLESPACE "CUSTOMTMP" ACCOUNT UNLOCK;

GRANT "CONNECT" TO "CUSTOM";
GRANT "RESOURCE" TO "CUSTOM";
GRANT create session TO "CUSTOM";
GRANT ALTER ANY INDEX TO "CUSTOM";
GRANT ALTER ANY SEQUENCE TO "CUSTOM";
GRANT ALTER ANY TABLE TO "CUSTOM";
GRANT ALTER ANY TRIGGER TO "CUSTOM";
GRANT CREATE ANY INDEX TO "CUSTOM";
GRANT CREATE ANY SEQUENCE TO "CUSTOM";
GRANT CREATE ANY SYNONYM TO "CUSTOM";
GRANT CREATE ANY TABLE TO "CUSTOM";
GRANT CREATE ANY TRIGGER TO "CUSTOM";
GRANT CREATE ANY VIEW TO "CUSTOM";
GRANT CREATE PROCEDURE TO "CUSTOM";
GRANT CREATE PUBLIC SYNONYM TO "CUSTOM";
GRANT CREATE TRIGGER TO "CUSTOM";
GRANT CREATE VIEW TO "CUSTOM";
GRANT DELETE ANY TABLE TO "CUSTOM";
GRANT DROP ANY INDEX TO "CUSTOM";
GRANT DROP ANY SEQUENCE TO "CUSTOM";
GRANT DROP ANY TABLE TO "CUSTOM";
GRANT DROP ANY TRIGGER TO "CUSTOM";
GRANT DROP ANY VIEW TO "CUSTOM";
GRANT INSERT ANY TABLE TO "CUSTOM";
GRANT QUERY REWRITE TO "CUSTOM";
GRANT SELECT ANY TABLE TO "CUSTOM";
GRANT UNLIMITED TABLESPACE TO "CUSTOM";
GRANT CREATE JOB TO "CUSTOM";
GRANT CREATE ANY JOB TO "CUSTOM";
