package com.magicpigeon.i18n.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 07 11:32:06 BST 2017
// ---------------------------------------------------------------------
public interface I18AppModule extends ApplicationModule {
    Map<String, String> getResourceBundle(String localeStr);
}

